### ISSUE TITLE
Observing "Patching failed with inconsistencies" warning, but status is patched successfully

### ISSUE THREAD

**Issue by ps-jay** [nolar/kopf#574] opened 2020-11-03 23:48 UTC
## Question

I'm observing a warning about "Patching failed with inconsistencies" .. but it appears to me that the status has been successfully patched.

I've checked the RBAC permissions, but they seem okay.

I've added some debugging to https://github.com/nolar/kopf/blob/0.28/kopf/reactor/effects.py that looks like this:
```
     if patch:
+        logger.debug(f"Body: {body!r}")
         logger.debug(f"Patching with: {patch!r}")
         resulting_body = await patching.patch_obj(resource=resource, patch=patch, body=body)
+        logger.debug(f"Resulting body: {resulting_body!r}")
         inconsistencies = diffs.diff(patch, resulting_body, scope=diffs.DiffScope.LEFT)
```

Here's the output of that debugging:
```
[2020-11-03 23:29:05,525] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Body: {'apiVersion': 'reece.tech/v1alpha1', 'kind': 'CloudformationDeployment', 'metadata': {'annotations': {'kopf.zalando.org/last-handled-configuration': '{"spec": {"stacks": [{"assume_role": "arn:aws:iam::123456789000:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-one-trsdev05", "preserve_tags": ["^reecetech:.*$", "phileatseggs"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-one-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "See, other tags work too"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}, {"assume_role": "arn:aws:iam::065001841352:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-two-trsdev05", "preserve_tags": ["^reecetech:.*$", "foobarbazspam"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-two-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "Because why stop at the Reece mandatory ones?"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}]}}'}, 'creationTimestamp': '2020-11-02T06:30:59Z', 'finalizers': ['kopf.zalando.org/KopfFinalizerMarker'], 'generation': 5, 'managedFields': [{'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {}}, 'manager': 'Go-http-client', 'operation': 'Update', 'time': '2020-11-02T06:30:59Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:stacks': {}}}, 'manager': 'dashboard', 'operation': 'Update', 'time': '2020-11-03T23:20:07Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kopf.zalando.org/last-handled-configuration': {}}, 'f:finalizers': {'.': {}, 'v:"kopf.zalando.org/KopfFinalizerMarker"': {}}}, 'f:status': {'.': {}, 'f:complete': {}, 'f:deleting': {}, 'f:failed': {}, 'f:rolled_back': {}, 'f:stacks': {}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2020-11-03T23:20:08Z'}], 'name': 'jayp-app-cloudformation-stacks-trsdev05', 'namespace': 'trsdev05', 'resourceVersion': '624106164', 'selfLink': '/apis/reece.tech/v1alpha1/namespaces/trsdev05/cloudformationdeployments/jayp-app-cloudformation-stacks-trsdev05', 'uid': '8bf6eb51-9c00-4c75-8778-58620b67fc16'}, 'spec': {'stacks': [{'assume_role': 'arn:aws:iam::123456789000:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-one-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'phileatseggs'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-one-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'See, other tags work too'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}, {'assume_role': 'arn:aws:iam::065001841352:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-two-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'foobarbazspam'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-two-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'Because why stop at the Reece mandatory ones?'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}]}, 'status': {'complete': False, 'deleting': False, 'failed': False, 'rolled_back': False, 'stacks': [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}]}}
[2020-11-03 23:29:05,525] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Patching with: {'status': {'stacks': [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}], 'complete': True}}
[2020-11-03 23:29:05,586] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Resulting body: {'status': {'apiVersion': 'reece.tech/v1alpha1', 'kind': 'CloudformationDeployment', 'metadata': {'annotations': {'kopf.zalando.org/last-handled-configuration': '{"spec": {"stacks": [{"assume_role": "arn:aws:iam::123456789000:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-one-trsdev05", "preserve_tags": ["^reecetech:.*$", "phileatseggs"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-one-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "See, other tags work too"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}, {"assume_role": "arn:aws:iam::065001841352:role/basic/kloudformator-assume-role", "name": "jayp-app-stack-two-trsdev05", "preserve_tags": ["^reecetech:.*$", "foobarbazspam"], "region": "ap-southeast-2", "tags": {"CostCentre": 3973, "Environment": "infra", "Name": "jayp-app-stack-two-trsdev05", "Owner": "Delivery Engineering", "SomeOtherTag": "Because why stop at the Reece mandatory ones?"}, "template": "---\\nAWSTemplateFormatVersion: \'2010-09-09\'\\nDescription: A template that does nothing\\n\\nConditions:\\n  HasNot: !Equals [ \'true\', \'false\' ]\\n\\n# dummy resource, never created because of the Condition\\nResources:\\n  NullResource:\\n    Type: \'Custom::NullResource\'\\n    Condition: HasNot\\n"}]}}'}, 'creationTimestamp': '2020-11-02T06:30:59Z', 'finalizers': ['kopf.zalando.org/KopfFinalizerMarker'], 'generation': 5, 'managedFields': [{'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {}}, 'manager': 'Go-http-client', 'operation': 'Update', 'time': '2020-11-02T06:30:59Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:spec': {'f:stacks': {}}}, 'manager': 'dashboard', 'operation': 'Update', 'time': '2020-11-03T23:20:07Z'}, {'apiVersion': 'reece.tech/v1alpha1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kopf.zalando.org/last-handled-configuration': {}}, 'f:finalizers': {'.': {}, 'v:"kopf.zalando.org/KopfFinalizerMarker"': {}}}, 'f:status': {'.': {}, 'f:complete': {}, 'f:deleting': {}, 'f:failed': {}, 'f:rolled_back': {}, 'f:stacks': {}}}, 'manager': 'kopf', 'operation': 'Update', 'time': '2020-11-03T23:29:05Z'}], 'name': 'jayp-app-cloudformation-stacks-trsdev05', 'namespace': 'trsdev05', 'resourceVersion': '624112539', 'selfLink': '/apis/reece.tech/v1alpha1/namespaces/trsdev05/cloudformationdeployments/jayp-app-cloudformation-stacks-trsdev05/status', 'uid': '8bf6eb51-9c00-4c75-8778-58620b67fc16'}, 'spec': {'stacks': [{'assume_role': 'arn:aws:iam::123456789000:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-one-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'phileatseggs'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-one-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'See, other tags work too'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}, {'assume_role': 'arn:aws:iam::065001841352:role/basic/kloudformator-assume-role', 'name': 'jayp-app-stack-two-trsdev05', 'preserve_tags': ['^reecetech:.*$', 'foobarbazspam'], 'region': 'ap-southeast-2', 'tags': {'CostCentre': 3973, 'Environment': 'infra', 'Name': 'jayp-app-stack-two-trsdev05', 'Owner': 'Delivery Engineering', 'SomeOtherTag': 'Because why stop at the Reece mandatory ones?'}, 'template': "---\nAWSTemplateFormatVersion: '2010-09-09'\nDescription: A template that does nothing\n\nConditions:\n  HasNot: !Equals [ 'true', 'false' ]\n\n# dummy resource, never created because of the Condition\nResources:\n  NullResource:\n    Type: 'Custom::NullResource'\n    Condition: HasNot\n"}]}, 'status': {'complete': True, 'deleting': False, 'failed': False, 'rolled_back': False, 'stacks': [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}]}}}
[2020-11-03 23:29:05,586] kopf.objects         [WARNING ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Patching failed with inconsistencies: (('remove', ('status', 'stacks'), [{'name': 'jayp-app-stack-one-trsdev05', 'status': 'UPDATE_COMPLETE'}, {'name': 'jayp-app-stack-two-trsdev05', 'status': 'UPDATE_COMPLETE'}], None), ('remove', ('status', 'complete'), True, None))
[2020-11-03 23:29:05,687] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Something has changed, but we are not interested (the essence is the same).
[2020-11-03 23:29:05,687] kopf.objects         [DEBUG   ] [trsdev05/jayp-app-cloudformation-stacks-trsdev05] Handling cycle is finished, waiting for new changes since now.
```

Here's the output of `kubectl` showing that the status seems to be okay:

```
$ kubectl get cfndeploys -o=json --namespace=trsdev05 jayp-app-cloudformation-stacks-trsdev05
{
    "apiVersion": "reece.tech/v1alpha1",
    "kind": "CloudformationDeployment",
<...snip...>
    "status": {
        "complete": true,
        "deleting": false,
        "failed": false,
        "rolled_back": false,
        "stacks": [
            {
                "name": "jayp-app-stack-one-trsdev05",
                "status": "UPDATE_COMPLETE"
            },
            {
                "name": "jayp-app-stack-two-trsdev05",
                "status": "UPDATE_COMPLETE"
            }
        ]
    }
}
```

I'm wondering if I'm doing something wrong?  Is this a false alarm?  Do I need to fix something?

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

`Patching` `failed` `inconsistencies`

**Comment by neocorp** [comment] 2020-11-05 12:28
@ps-jay I'm receiving the same warning with 0.28 recently even though everything's ok and no failures at all. Would be great if we can get some guidance on this.

**Comment by nolar** [comment] 2020-11-05 13:06
Thanks for reporting. Indeed, it looks like a bug somewhere in these lines: https://github.com/nolar/kopf/blob/0.28/kopf/clients/patching.py#L67-L84

In the resulting body in your logs, the actual status is located in `patched_body["status"]["status"]` (2nd level field).

It looks like K8s API responds with the whole body to `PATCH .../status` — instead of the expected sub-resource's body as it would be expected with REST.

Probably fixable by a one-line change like this or similar to it:

```diff
-            patched_body['status'] = await response.json()
+            patched_body['status'] = await response.json().get('status')
```

I will need to re-verify with the K8s API reference — it seems, I've misread it in the first attempt.

Meanwhile, you can send a PR with this fix (plus some extra tests that would catch this situation) — if you wish. Or I will do it a bit later. 

I've created a maintenance branch [`release/0.28`](https://github.com/nolar/kopf/tree/release/0.28), on which you can base your fix, and against which you can send a PR instead of the master branch — so that it would be a 0.28.1 quick release (releasable immediately) instead of 0.29 (unknown schedule).

_Links: introduced in #527._

**Comment by neocorp** [comment] 2020-11-09 16:20
@nolar I want to contribute and start by fixing this issue. Can you help me get started?

**Comment by nolar** [comment] 2020-11-11 21:17
@neocorp Sure. The repo is made to have no barriers for contributions, so you can just try. If there are questions — feel free to reach me directly in any messengers/chats/social networks/email — I am googleable.

* https://kopf.readthedocs.io/en/latest/contributing/

_(You can skip the GPG and DCO parts, those are some leftovers after forking.)_

In general, clone it, `pip install -r requirements.txt`, unit-test it without changes (`pytest`). The docs currently document Minikube usage everywhere, and it works, but I suggest K3s/K3d for a lightweight K8s cluster locally (a matter of preferences). With the local cluster, you can also run it or its e2e tests.

Then make the changes, check if they work as intended, commit and push, and create a PR. I've provided the hint where to look for the relevant code in the comment above. Then check which unit-tests break, and fix them. If none of them reflects this proper behaviour, add one or two (should be enough for a one-line change).

I will assign this issue to you, just in case. All the best! ;-)

**Comment by nolar** [comment] 2020-11-11 21:19
@neocorp Ah! A little thing I forgot to mention. Please, after cloning, `git checkout release/0.28`, and base your changes on that branch, not on `master`. And when creating the pull request, also change the `master` branch to `release/0.28` in GitHub's UI.

I will merge it to 0.28.1, and then will merge the same commit to the `master` (via a separate PR). It is easier to merge commits upward in git, than to backport changes by multiple separate commits. Though, it is also doable if needed.

**Comment by somaliz** [comment] 2020-11-16 10:08
+1 an ETA ? @neocorp

**Comment by iExalt** [comment] 2020-12-02 02:50
@nolar @neocorp Seeing that warning pop up every time I changed the status field really bugged me, so I took the liberty of submitting a PR that should close out this issue.

@nolar Thank you for the detailed triage [here](https://github.com/nolar/kopf/issues/574#issuecomment-725666114), it made submitting my first open source PR quite smooth. Go easy on me :)

**Comment by nolar** [comment] 2020-12-03 23:16
Fixed and released in [`kopf==0.28.1`](https://github.com/nolar/kopf/releases/tag/0.28.1). Thanks @iExalt!

**Comment by nolar** [comment] 2020-12-03 23:17
Feel free to reopen if the issue reappears.

**Closed as completed by nolar** 2020-12-03 23:16 UTC
Labels: bug

**Comment by ztaylor54** [comment] 2020-12-11 01:58
I'm actually running into this same error message right now, but it seems that patching _is_ actually failing using `kopf==0.28.1`. I rolled back to `0.28` with the same results.

In my handler I'm simply returning `{'foo': 'bar'}` and getting the following:

```
[2020-12-10 17:49:28,568] kopf.objects         [INFO    ] [default/test] Handler 'create_fn' succeeded.
[2020-12-10 17:49:28,568] kopf.objects         [INFO    ] [default/test] Creation event is processed: 1 succeeded; 0 failed.
[2020-12-10 17:49:28,568] kopf.objects         [DEBUG   ] [default/test] Patching with: {'status': {'create_fn': {'foo': 'bar'}}, 'metadata': {'annotations': {'kopf.zalando.org/last-handled-configuration': '<...>'}}}
[2020-12-10 17:49:28,630] kopf.objects         [WARNING ] [default/test] Patching failed with inconsistencies: (('remove', ('status',), {'create_fn': {'foo': 'bar'}}, None),)
[2020-12-10 17:49:28,733] kopf.objects         [DEBUG   ] [default/test] Something has changed, but we are not interested (the essence is the same).
[2020-12-10 17:49:28,734] kopf.objects         [DEBUG   ] [default/test] Handling cycle is finished, waiting for new changes since now.
```

Could this be related to this issue? If not, I can open another. Thanks!

**Comment by nolar** [comment] 2020-12-11 12:19
@ztaylor54 Do you have `x-kubernetes-preserve-unknown-fields: true` set as described here in the notes? Either for the whole object, or only for the `.status` field.

* https://kopf.readthedocs.io/en/stable/configuration/?highlight=%22x-kubernetes-preserve-unknown-fields%22#handling-progress

**Comment by ztaylor54** [comment] 2020-12-11 18:40
@nolar Adding

```yaml
status:
  type: object
  x-kubernetes-preserve-unknown-fields: true
```

to the schema of my CRD solved the issue, thanks!

However, I am confused by some of the documentation on the page you linked. It mentions that I should be able to configure the status to be stored in the annotations (and that this is the better way going forward), so before editing my CRD to allow the status field, I tried:

```python
import kopf

@kopf.on.startup()
def configure(settings: kopf.OperatorSettings, **_):
    settings.persistence.progress_storage = kopf.AnnotationsProgressStorage(prefix='my-op.example.com')
```

But adding this to the operator only added the following to the annotations:

```
my-op.example.com/kopf-managed: "yes"
```

and it seemed like it was still trying to store the handler return in the status field:

```
[2020-12-11 10:28:54,496] kopf.objects         [INFO    ] [default/test] Creation event is processed: 1 succeeded; 0 failed.
[2020-12-11 10:28:54,497] kopf.objects         [DEBUG   ] [default/test] Patching with: {'metadata': {'annotations': {'my-op.example.com/kopf-managed': 'yes', 'kopf.zalando.org/last-handled-configuration': '<...>'}}, 'status': {'create_fn': {'foo': 'bar'}}}
[2020-12-11 10:28:54,588] kopf.objects         [WARNING ] [default/test] Patching failed with inconsistencies: (('remove', ('status',), {'create_fn': {'foo': 'bar'}}, None),)
[2020-12-11 10:28:54,694] kopf.objects         [DEBUG   ] [default/test] Something has changed, but we are not interested (the essence is the same).
[2020-12-11 10:28:54,694] kopf.objects         [DEBUG   ] [default/test] Handling cycle is finished, waiting for new changes since now.
```

Perhaps I've misunderstood the documentation? In any case, the documentation around handlers (including the tutorial sections [here](https://kopf.readthedocs.io/en/stable/walkthrough/updates/) would surely benefit from some clarification on this issue. Thanks again!

**Comment by nolar** [comment] 2020-12-11 19:13
@ztaylor54 

The handlers' results are stored only in the statuses. They are not connected to the framework's internal storage of handler progression or the "diff-base" field (aka last-handled-configuration). In other words, this aspect is fully in the operator developers control, so it requires no attention now.

There is no clear decision yet on how to deliver the results (and to where), so they are stored the way they were done initially (some early-stage conventions) — to the status field. If that is not the goal, use can use the `patch` kwarg to store any values in any fields.

When and if this changes, storing to `.status.{id}` will remain the default behaviour, and other places would have to be explicitly configured.

---

Regarding the annotations — all is done correctly in your example. Not only the kopf-managed annotation is stored, but the last-handled-configuration, as seen in your logs (read nearby about the "diff-base" storages on the same docs page to customise its name).

If you will put a breakpoint inside of any handler (assuming there is more than one of that kind: i.e. 2+), or if you make a handler to `raise kopf.TemporaryError("...", delay=60)`, or will make the processing delayed in any other ways, you will see other per-handler annotations stored by Kopf. These annotations (so as the status fields, actually) are removed as soon as the operator is done with processing the change.

This does not show up if you have at most 1 handler of each purpose (creation/update/deletion) — and I see `1 succeeded; 0 failed` — in that case, the whole processing is done in one jump, so there is no need to store the temporary state. The temporary data is stored only when there is need for that.

---

Regarding the tutorial — I agree here, that note could be highly useful to avoid confusion in the initial journey. The tutorial was not updated for long time, and that "x-…-preserve-…" field and schemas cause troubles for quite a while — since K8s 1.16.

I would appreciate if you send a PR with this warning/recommendation for the tutorial. Maybe it is even worth extracting this lengthy "Note" block to https://kopf.readthedocs.io/en/stable/troubleshooting/ — and linking there from multiple places in the documentation.

Also, if you have any ideas on a better tutorial story — please suggest in #604

**Comment by ztaylor54** [comment] 2020-12-11 19:34
@nolar Thanks for such a comprehensive -- and quick (!) -- answer to my question. I now have a deeper understanding of what's going on here.

Sure, I can submit a PR for the documentation. I will work on it this weekend.
