### ISSUE TITLE
Cli forces --log-format

### ISSUE THREAD

**Issue by mnarodovitch** [nolar/kopf#774] opened 2021-05-14 11:49 UTC
## Long story short

`kopf run` doesn't run without `--log-format`

## Description

```bash
$ kopf run
Usage: kopf run [OPTIONS] [PATHS]...
Try 'kopf run --help' for help.

Error: Invalid value for '--log-format': <LogFormat.FULL: '[%(asctime)s] %(name)-20.20s [%(levelname)-8.8s] %(message)s'> is not one of 'plain', 'full', 'json'.
```

```bash
$ kopf run --log-format full
...does the magic
```

## Environment

* Kopf version: kopf, version 1.31.0
* Python version: Python 3.7.7
* OS/platform: Ubuntu

**Comment by nolar** [comment] 2021-05-14 12:01
That is a duplicate of #767, see https://github.com/nolar/kopf/issues/767#issuecomment-840495122

**Closed as completed by nolar** 2021-05-14 12:01 UTC
Labels: bug
